[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known-first-party = ["src"]

[tool.ruff]
# Same as Black
line-length = 88
indent-width = 4

# Assume Python 3.10
target-version = "py310"

# Exclude files
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
]

[tool.ruff.lint]
# Enable all rules by default
select = ["ALL"]

# Ignore certain rules
ignore = [
    "E501",  # Never enforce line length
    "D406",  # Section name should end with a newline
    "A002",  # Argument shadows built-in
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]
"src/video/processor.py" = ["PLR0913"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"